name: Jenkins Pipeline for RPM and DEB

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t jenkins-image .

      - name: Run Jenkins container
        run: |
          docker run -d -p 8080:8080 --name jenkins-container jenkins-image

      - name: Wait for Jenkins to start
        run: |
          sleep 30

      - name: Trigger Jenkins job to build RPM and DEB
        run: |
          curl -X POST "http://localhost:8080/job/build-job/build" --user jenkins:your_jenkins_token
