name: Build RPM Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-rpm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set execute permissions for rpm_builder.sh
        run: chmod +x ./rpm_builder.sh

      - name: Run rpm_builder.sh
        run: ./rpm_builder.sh

      - name: Set execute permissions for deb_builder.sh
        run: chmod +x ./deb_builder.sh

      - name: Run deb_builder.sh
        run: ./deb_builder.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: |
            ~/rpmbuild/RPMS/
            ~/rpmbuild/SRPMS/
            /home/runner/*.deb
